### ISSUE TITLE
Crash after unpinning app from the launcher

### ISSUE THREAD

**Issue by iBeliever** [qmlos/shell#28]
Stacktrace:

```
#0  0x00007ffff2f6ba77 in ?? () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff2f6c217 in QObject::disconnectImpl(QObject const*, void**, QObject const*, void**, QMetaObject const*) () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff1e1906f in QQuickPopup::setParentItem(QQuickItem*) () from /usr/lib/libQt5QuickTemplates2.so.5
#3  0x00007ffff1e3281a in QQuickToolTipAttached::show(QString const&, int) () from /usr/lib/libQt5QuickTemplates2.so.5
#4  0x00007ffff1e41b14 in ?? () from /usr/lib/libQt5QuickTemplates2.so.5
#5  0x00007ffff1e4220b in QQuickToolTipAttached::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libQt5QuickTemplates2.so.5
#6  0x00007ffff6251832 in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyPrivate::WriteFlag>) ()
   from /usr/lib/libQt5Qml.so.5
#7  0x00007ffff6253043 in QQmlPropertyPrivate::writeValueProperty(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyPrivate::WriteFlag>) ()
   from /usr/lib/libQt5Qml.so.5
#8  0x00007ffff62c079c in QQmlBinding::write(QQmlPropertyData const&, QV4::Value const&, bool, QFlags<QQmlPropertyPrivate::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#9  0x00007ffff62c18e5 in QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#10 0x00007ffff62c222e in QQmlBinding::refresh() () from /usr/lib/libQt5Qml.so.5
#11 0x00007ffff6297044 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#12 0x00007ffff624119c in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib/libQt5Qml.so.5
#13 0x00007ffff2f69c0c in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff6297044 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#15 0x00007ffff624119c in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib/libQt5Qml.so.5
#16 0x00007ffff2f69c0c in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff6a20888 in QQuickMouseArea::setHovered(bool) () from /usr/lib/libQt5Quick.so.5
#18 0x00007ffff6a219db in QQuickMouseArea::hoverEnterEvent(QHoverEvent*) () from /usr/lib/libQt5Quick.so.5
#19 0x00007ffff699f068 in QQuickItem::event(QEvent*) () from /usr/lib/libQt5Quick.so.5
#20 0x00007ffff3e58e3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff3e605b1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff2f3dc80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#23 0x00007ffff69b1b00 in QQuickWindow::sendEvent(QQuickItem*, QEvent*) () from /usr/lib/libQt5Quick.so.5
#24 0x00007ffff69b44f6 in QQuickWindowPrivate::sendHoverEvent(QEvent::Type, QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool) ()
```

**Comment by iBeliever** [comment]
It looks like this crashes because there's still a reference to the deleted parent of the tooltip, which I think would be the launcher delegate. It looks like this will be fixed in Qt 5.7.1 by https://github.com/qt/qtquickcontrols2/commit/7c07c60ff17974621fea932a18cc2e652d17ab78.
